version: '3.1'

services:
  db:
    image: "mongo:latest"
    expose:
      - "27017"
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
  api:
    build:
      context: ./api
    depends_on:
      - db
    environment:
      - EXPRESS_PORT=8080
      - DB=mongodb://db:27017/cabchain
    volumes:
      - /api/node_modules
      - ./api:/api